dappnode_package.json
docker-compose.yml

"ethchain.dnp.dappnode.eth": "0.1.13",
"ethforward.dnp.dappnode.eth": "0.1.5",

Update ethchain and ethforward

---

dappnode_package.json
docker-compose.yml

- Fix bug crashing the UI on Safari browsers https://github.com/dappnode/DNP_DAPPMANAGER/pull/407

v0.2.38 Release

---

dappnode_package.json

- Added DNP_HTTPS package
- Bump dappmanager version

Include HTTPS for new release

---

.github/workflows/main.yml

Due to possible changes core packages releases, it is useful to create the DNP_CORE release on demand

create dnp_core release on demmand

---

src/scripts/edit_user_watches.sh
src/upgrades/upgrade_010.sh

User watches require to be executed with sudo.

Edit user watches with `nsenter`

---

src/upgrades/upgrade_009.sh
src/upgrades/upgrade_010.sh

Copy latest:
- script
- Profile
- welcome message

Copy latest script and profile

---

src/grab_hashes.sh

Add cons client hashes to the `packages-content-hash.csv` file

Add cons clients hashes

---

src/upgrades/upgrade_012.sh

Add dappnode ipfs peer

---

src/upgrades/upgrade_012.sh

Set docker inspect only for dncore network

Set docker inspect only for dncore network

---

src/scripts/enable_unattended_upgrades.sh

Modify, install and update needrestart if needed

Modify, install and update needrestart if needed

---

src/scripts/enable_unattended_upgrades.sh

Relocate needrestart modification file

Relocate needrestart modification file

---

dappnode_package.json

Bump ipfs to 0.2.21

---

src/scripts/enable_chrony.sh

Non interactive frontend for chrony script

Export non interactive

---

dappnode_package.json

Manifest description typo

---

docker-compose.yml

Remove legacy dns and hardcoded IP

Remove legacy dns and hardcoded IP

---

dappnode_package.json

Add warning on minorUpdate 0.3.0

Add warning on minorUpdate

---

dappnode_package.json

Add optional dependencies to core so they get updated if already installed

Add optional dependencies to core

---

.github/workflows/main.yml

adding vpn, wireguard and https versions as optional dependencies in workflows

optionalDependencies to workflows

---

dappnode_package.json

Bump ethical to 0.1.3

---

dappnode_package.json

Bump htttps optional dependency to 0.2.2

Bump htttps to 0.2.2

---

dappnode_package.json

Remove ethical metrics from optional dependencies

Remove ethical metrics from optional dependencies

---

dappnode_package.json

Remove https optional dependencies

Remove https optional dependencies
